<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.iam</groupId>
        <artifactId>iam-system</artifactId>
        <version>0.0.1-SNAPSHOT</version>
    </parent>

    <artifactId>iam-authn</artifactId>
    <name>iam-authn</name>
    <description>Authentication Engine for Human and M2M flows</description>

    <dependencies>
        <dependency>
            <groupId>com.iam</groupId>
            <artifactId>iam-common</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.iam</groupId>
            <artifactId>iam-directory</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.iam</groupId>
            <artifactId>iam-crypto</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.security</groupId>
            <artifactId>spring-security-crypto</artifactId>
        </dependency>
    </dependencies>
</project>